name: Release
on:
  push:
    branches: [release/1.0.1]

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - name: Pull Request
        uses: dustinirving/create-pr@v1.0.1
        with:
          title: 'Open PR'
          body: '<h3>Summary</h3><p>Body...</p>'
          head: 'release/1.0.1'
          base: 'main'
          labels: 'Github Actions'
          reviewers: 'dustinirving'